import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../data/models/employee_model.dart';
import '../core/services/supabase_service.dart';
import '../core/services/local_db_service.dart';

class EmployeeViewModel extends StateNotifier<AsyncValue<List<Employee>>> {
  final SupabaseService _supabaseService;
  final LocalDbService _localDb = LocalDbService();
  List<Employee> _allEmployees = [];

  EmployeeViewModel(this._supabaseService) : super(const AsyncValue.loading()) {
    loadEmployees();
  }

  // Load employee master list
  Future<void> loadEmployees() async {
    state = const AsyncValue.loading();
    try {
      if (!_supabaseService.isOnline) {
        // Query offline local SQLite cache
        final localData = await _localDb.query('employees');
        _allEmployees = localData.map((e) => Employee.fromJson(e)).toList();
        
        // Seed some mock employees if cache is empty
        if (_allEmployees.isEmpty) {
          _allEmployees = _generateMockEmployees();
          for (final emp in _allEmployees) {
            await _localDb.insert('employees', emp.toJson());
          }
        }
        state = AsyncValue.data(_allEmployees);
        return;
      }

      // Query Supabase
      final response = await _supabaseService.select(table: 'profiles', orderCol: 'employee_id');
      _allEmployees = response.map((e) => Employee.fromJson(e)).toList();
      state = AsyncValue.data(_allEmployees);
    } catch (e) {
      state = AsyncValue.error(e, StackTrace.current);
    }
  }

  // Search/Filter helper
  void searchEmployees(String query, String deptFilter) {
    if (state.value == null) return;
    
    var filtered = _allEmployees;
    
    if (deptFilter.isNotEmpty && deptFilter != 'All') {
      filtered = filtered.where((e) => e.departmentName.toLowerCase() == deptFilter.toLowerCase()).toList();
    }
    
    if (query.isNotEmpty) {
      filtered = filtered.where((e) =>
        e.name.toLowerCase().contains(query.toLowerCase()) ||
        e.employeeId.toLowerCase().contains(query.toLowerCase())
      ).toList();
    }
    
    state = AsyncValue.data(filtered);
  }

  // Add new employee
  Future<bool> addEmployee(Employee employee) async {
    try {
      if (!_supabaseService.isOnline) {
        // Queue offline insertion and add to local database cache
        await _localDb.insert('employees', employee.toJson());
        await _localDb.queueSync('INSERT', 'profiles', employee.toJson());
        
        _allEmployees.add(employee);
        state = AsyncValue.data(List.from(_allEmployees));
        return true;
      }

      final res = await _supabaseService.insert(table: 'profiles', values: employee.toJson());
      if (res != null) {
        final newEmp = Employee.fromJson(res);
        _allEmployees.add(newEmp);
        state = AsyncValue.data(List.from(_allEmployees));
        return true;
      }
    } catch (e) {
      state = AsyncValue.error(e, StackTrace.current);
    }
    return false;
  }

  // Import Employees from CSV format
  Future<int> importEmployeesFromCsv(String csvContent) async {
    int importCount = 0;
    try {
      final lines = csvContent.split('\n');
      for (var line in lines) {
        line = line.trim();
        if (line.isEmpty || line.startsWith('Employee ID') || line.startsWith('id')) continue; // skip header
        
        final parts = line.split(',');
        if (parts.length >= 6) {
          final id = parts[0].trim();
          final name = parts[1].trim();
          final desig = parts[2].trim();
          final dept = parts[3].trim();
          final shift = parts[4].trim();
          final email = parts[5].trim();
          
          final newEmp = Employee(
            id: 'temp-$id', // auth reference generated by supabase auth
            employeeId: id,
            name: name,
            designation: desig,
            departmentName: dept,
            shiftName: shift,
            email: email,
            role: 'employee',
            status: 'active',
          );

          await addEmployee(newEmp);
          importCount++;
        }
      }
    } catch (e) {
      state = AsyncValue.error(e, StackTrace.current);
    }
    return importCount;
  }

  List<Employee> _generateMockEmployees() {
    return [
      Employee(
        id: '1',
        employeeId: 'EMP-001',
        name: 'Mohit Kumar (Admin)',
        designation: 'Director',
        departmentName: 'Administration',
        shiftName: 'Shift A (Morning)',
        email: 'admin@dms.com',
        role: 'super_admin',
        status: 'active',
      ),
      Employee(
        id: '2',
        employeeId: 'EMP-002',
        name: 'Preeti Sen (HR)',
        designation: 'HR Executive',
        departmentName: 'Human Resources',
        shiftName: 'Shift A (Morning)',
        email: 'hr@dms.com',
        role: 'hr',
        status: 'active',
      ),
      Employee(
        id: '3',
        employeeId: 'EMP-003',
        name: 'Rajesh Sharma',
        designation: 'Supervisor',
        departmentName: 'Operations',
        shiftName: 'Shift B (Evening)',
        email: 'supervisor@dms.com',
        role: 'supervisor',
        status: 'active',
      ),
      Employee(
        id: '4',
        employeeId: 'EMP-004',
        name: 'Sanjay Singh',
        designation: 'Technician',
        departmentName: 'Engineering',
        shiftName: 'Shift C (Night)',
        email: 'employee@dms.com',
        role: 'employee',
        status: 'active',
      ),
    ];
  }
}

final employeeViewModelProvider = StateNotifierProvider<EmployeeViewModel, AsyncValue<List<Employee>>>((ref) {
  final supabaseService = ref.watch(supabaseServiceProvider);
  return EmployeeViewModel(supabaseService);
});
